### PR TITLE
switch release to 1.0.4

### PR DESCRIPTION
**Pull request by hariharan-devarajan**
Updated the release version to 1.0.4 and fixed documents for the same.

### CODE REVIEW

**Comment by hariharan-devarajan** [comment]
@bertwesarg This should fix the issue with libtool you mentioned.

**Comment by bertwesarg** [comment]
no, it only reverts the changes, but does not update the libtool version for the release

do you really want the 'develop'-merge commit in this PR to 'develop'?

may I ask why #103 is not in this release? without this fix the new release has no value for us

**Comment by hariharan-devarajan** [comment]
@bertwesarg BTW I will call the new release 2.1.0 so that from now on we make the library version and documentation match correctly. Thank you again for sharing the document for libtool's versioning.

**Comment by hariharan-devarajan** [comment]
Oh i see now. I agree with your argument. I will let the library name be same for the purpose of drop-in replacements.

**Comment by bertwesarg** [comment]
the increment to `age` got lost

**Pull request merged**
