### PR TITLE
Search for the latest symbol version

### LINKED ISSUE #102: Wraps different symbol version
GOTCHA currently does not honor symbol versions used in glibc.

Case at hands: I wanted to wrap the `pthread_cond_*` family of functions. Though in glibc there are two symbol versions:

 - `GLIBC_2.2.5`
 - `GLIBC_2.3.2`

Unfortunately, for glibc 2.31 (Ubuntu 20.04), GOTCHA wraps `pthread_cond_init` to `__pthread_cond_init_2_0` but `pthread_cond_broadcast` to `__pthread_cond_broadcast`. I.e., one to the old ABI and the other to the new ABI which breaks at runtime.

The reason seems to be that the order of the symbols in `libpthread-2.31.so` is:

```
   267: 0000000000010610    31 FUNC    GLOBAL DEFAULT   16 pthread_cond_init@GLIBC_2.2.5
   268: 000000000000ed90    58 FUNC    GLOBAL DEFAULT   16 pthread_cond_init@@GLIBC_2.3.2
   205: 0000000000010290   894 FUNC    GLOBAL DEFAULT   16 pthread_cond_broadcast@@GLIBC_2.3.2
   206: 00000000000107c0   101 FUNC    GLOBAL DEFAULT   16 pthread_cond_broadcast@GLIBC_2.2.5
```

### PR DESCRIPTION
**Pull request by bertwesarg**
Closes #102

### CODE REVIEW

**Comment by daboehme** [comment]
Hi @bertwesarg , thanks for the report and the fix! I'll look into this in more detail, hopefully soon.

**Comment by hariharan-devarajan** [comment]
@bertwesarg In our new CI, which will be merged soon, we have access to the new glibc can you add a test case for this case?

**Review by hariharan-devarajan — CHANGES_REQUESTED** [review]
Lets add a test case as well to test these changes.

**Comment by hariharan-devarajan** [comment]
@bertwesarg I added the CI and coverage in the main develop branch. You can now pull in the latest to add a test case and check if the CI passes. Thanks for the effort.

**Comment by bertwesarg** [comment]
The CI is not the reason why there is no test. The subject is the problem. Newer glibc wont help here either. Even my testcase in #102 on the same system now resolves to the same version for the symbols, though the older one, but as long as these resolve to the same version, they work. It does only not work if they resolve to different versions. In that case there would be a segfault. But now I cannot even rely on this.

I tried to build by own shared library with symbol versions, but there it depends in which order the global symbols are defined. On my system the order was again indulgent to me and the latest symbol was first. So it also works without the fix.

**Comment by hariharan-devarajan** [comment]
> The CI is not the reason why there is no test. The subject is the problem. Newer glibc wont help here either. Even my testcase in #102 on the same system now resolves to the same version for the symbols, though the older one, but as long as these resolve to the same version, they work. It does only not work if they resolve to different versions. In that case there would be a segfault. But now I cannot even rely on this.
> 
> I tried to build by own shared library with symbol versions, but there it depends in which order the global symbols are defined. On my system the order was again indulgent to me and the latest symbol was first. So it also works without the fix.

We could try the following test, u can load the symbols through gotcha and dlvsym with version. And we can compare the symbol pointers to make sure they always load the latest. I understand we only have a happy case and not a sad case. But that is better than having no cases.

**Comment by bertwesarg** [comment]
The test already exercises this. If the wrong symbol would be wrapped, the test failes because the returned value is unexpected.

**Comment by bertwesarg** [comment]
I got it working now. Its important that the old and new symbols are in different CU/objects. Though the order on the linkline does not seem to matter.

**Review by hariharan-devarajan — APPROVED** [review]
The code changes now look good to me. Lets get matt opinion then we can merge.

**Pull request merged**
