### PR TITLE
[RFC] Feature: C++11 interface

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
It would be nice to program Gotcha using C++ niceness, rather than having to write out a bunch of prototypes and structs, instead being able to provide a function to be wrapped, and a wrapper as a lambda, and have things just work

This one is a template (oh ho ho) solution, there are known bugs in it, this is simply to clarify the interface. It is analogous to, but distinct from, [the Caliper solution](https://github.com/DavidPoliakoff/Caliper/blob/feature/heckin-gotcha/include/caliper/CaliGotcha.h). You can see an example in action [here](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/test/functional/app.cpp). To be a Gotcha interface, it needs three things: the function to be wrapped, the wrapper, and a way to get your underlying function. Now, the obvious interface 

```
gotcha_quick_wrap(malloc,[=](unsigned long size){
  //do something clever
});
```

Falls on its face, we have no way to get to the underlying "malloc" call. I solve this by making the underlying malloc the first argument to the lambda you pass in,

```
gotcha_quick_wrap(malloc,[=](magic_type_here underlying_malloc_fp, unsigned long size){
  //do something clever
  return underlying_malloc_fp(size);
});
```

There are alternatives involving storing things in maps, but I really like this version. Having the underlying function as an argument gives us a lot of freedom to mess around in the back end without impacting user code, we just have to eventually feed them a valid function pointer (or really, anything callable, but a function pointer is the smart thing to do).

Now on to the [implementation](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h). First, we know we're going to be passing around things a person might call as template arguments. [We need a way to extract information from those template arguments](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L37). The linked class is pretty well-understood, but provides various type aliases to get at things like the return value of a function pointer, to extract "R" from "R(*)(int,float,puppy)," and then a bunch of specializations so that we can accept a variety of function types (including pointers to member functions of C++ classes, an idea I have not yet played with, but will be playing with in the future).

For the real part of the problem, we need three things: a wrapper, the [name of a function](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L127), and [a way to get the underlying function](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L111).

The wrapper itself is a bit of a bear. The user wants to pass in a lambda which takes the original function pointer as an argument, but Gotcha has to redirect malloc to something with the same function signature as malloc. Here is where things get complicated. I need data, and it can't be an argument to the function. It also can't be a non-static member in the type, or the function which accesses it (the type we're redirecting malloc to) can't have the correct type signature. It also can't be global. What I do is essentially make every instance of this class a separate template instantiation by having an [integer template parameter](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L168) (int N) that is always distinct, so there is "static" data that is actually distinct per instance of the class. I guarantee distinctness by hiding the instantiation behind a [preprocessor macro](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L183), with the integer set to \_\_COUNTER\_\_, a portable macro which increments each time the compiler encounters it. This allows us to have a [static wrapper to redirect our target function to](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L136), which we [do in our constructor](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L130). From that function, we [call the wrapper the user provided, passing the original function pointer as the first argument to their wrapper](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L141). That concludes what exactly that class is actually doing.

The thing the user actually calls is [extremely sketchy](https://github.com/DavidPoliakoff/GOTCHA/blob/2a3c8a68a566dddcf2973d3d0575fa7a216e4295/include/gotcha/gotcha_cpp.h#L181), I don't do preprocessor macros. There are a few things I wanted to satisfy: I didn't want the user to have to use a complicated alias or function pointer type to refer to the function pointer to (for example) malloc, so I autogenerate a type alias original_malloc (or free, or whatever the user passes), but this code is pretty hideous, I wouldn't mind alternatives.

End of the day, you get something that lets you write

```
gotcha_quick_wrap(some_function,[=](original_some_function,some_functions_args){
   //do smart things
   auto return_value = original_some_function(some_functions_args)
   return return_value;
});
```

A little more disgustingly, you can add state to functions which are themselves stateless

```
int recorder = 0;
gotcha_quick_wrap(some_function,[&](original_some_function, int arg, some_functions_args){
   //do smart things
   auto return_value = original_some_function(some_functions_args)
   recorder = arg;
   return return_value;
});
```

There are a lot of possible shenanigans here, but that's the interface and a simple test, but one which includes stacking.

### CODE REVIEW

**Comment by mplegendre** [comment]
This is a reasonable start at a C++ interface.  It addresses some of my hallway concerns about mapping calls between the N-argument functions and the N+1-argument functions.  But I have other concerns:

- I'm worried about calling conventions.  On Windows/x86_64 (if memory serves correctly) there are different calling conventions between C++ and C.  We've created a C++ wrapper around every gotcha wrappee.  Are there any other platforms/compilers (that we care about) where having same signature in C++ and C produce different calling conventions?  If so, we're going to break across any of those functions.  We need to research this.  

- I'm generally concerned about the active() and unwrap() implementations.  The "active" decision seems fundamental to this--it says whether you're about to call a N+1 or N argument function.  It doesn't look like the implementation's done, but I think you're going to have to keep state to track where you are in the tool stack and what's the next part of the chain.  That's going to get very complicated.  What if users aborts out of the tool stack early?  What if they get half-way down a tool stack and switch to another wrapped function?   Can they support recursive calls into the wrapper?  Multiple threads going through the wrappers simultaneously?

The C gotcha interface avoids this by not tracking state.  The user is always the re-specifying current place in the tool chain with the wrapper identifier, which lets us look up the next step in the tool chain. 

- What does it look like when a user is specifying a large number of wrappers (e.g., wrapping all MPI calls).  If every wrapping operation takes a gotcha_quick_wrap call, does that mean they write a single "wrap_all_mpi()" function with 1000 lambdas in it?  That's going to be awkward maintenance.  Also, each wrapping operation has a high overhead of looking through GOT tables.  We currently aggregate that overhead by doing 1 iteration over GOT tables for all wrapping actions.  Do we now have to do N iterations over GOT tables?

- We'll need tool names and configurations as part of the C++ interface too.  I believe there's likely some way this interface could be extended to that, but I'd like get that straightened out in the C interface first.

**Comment by DavidPoliakoff** [comment]
I'll address these in order.

In the first, I'll have to claim ignorance. I can do some research, but I'm not sure where we would get in trouble off the top of my head. I have a hazy recollection that it's possible to manually specify the calling conventions of a function in either C or C++ (fastcall or cdecl or ____), that may be a good hedge.

The second: me too, I rewrote unwrap last night because it's objectively wrong (whoops). Unwrap is a bizarre one, it's extremely useful, I used the new version to make an interface where when the created runtime_wrapper is destroyed, "we go back to calling the original function." Quotes because that isn't exactly what happens, but it's what it looks like happens. So doing things like "replace mallocs _in this loop_ with MallocDujours" becomes possible (or activating and deactivating tracing of functions at different places, if you were interested in that kind of functionality). I think the thread-safety point is well taken, but that the solution there is documentation, ideally you would at the start of a function do your wraps, then call those functions, then unwrap

The third: I think the C++ interface to wrap_all_mpi is the C interface. I don't plan on this replacing the C interface, that would be a really bad idea. I might add some C++ conveniences to the C interface at some point, but at its core, the C interface is still a huge part of our workflow. I do take your point over the GOT batching, I think I have a solution sketched out.

The fourth: same. It's doable, and the "handles" I've started adding should help.

Now for my issues with the interface:

- In the default no handles form, it mallocs memory without freeing it. Moving to the form where it also frees memory is doable, but I don't know that everybody will understand RAII, we may have to move to a different way of managing the objects this system creates. Object lifetimes are important. Actually, your idea of batching may be how we solve this problem.

- The interface will allow you to take a pointer to a member function of a C++ class (benefit!), but will not actually wrap that function due to name mangling (rats!). There's a general problem with name mangling, but using the words "C++ interface" intensifies the perception that we support C++, which we don't in some places

- There are obvious extensions to this. Somebody may want to do something with the name of the function they wrapped, or do some [operation over each of the arguments](https://github.com/DavidPoliakoff/Caliper/blob/feature/heckin-gotcha/include/caliper/CaliFunctional.h#L272) (link is to a Caliper example). Having facilities for that would be handy. At the same time we worry about too much C++ cleverness, we should also worry about the cleverness we're missing

**Comment by DavidPoliakoff** [comment]
I just made a push that adds handles. It's still not worth merging, but this is a bit closer. Note that now, when the wrap statement goes out of scope (is destroyed), the wrapping it entails disappears, so [the "malloc" outside of the scope in which malloc_handle_2 exists](https://github.com/DavidPoliakoff/GOTCHA/blob/5fa7199c27f204a7d9e3fed22bf1f6cd9f8f33e8/test/functional/app.cpp#L58) doesn't have that wrapper applied, which is really quite cool. For reference, the output is

```
Allocation of size 24
Allocation of size 1
Allocation of size 80
Allocation of size 4080
Allocation of size 24
Outer malloc wrapper called on size 24
Allocation of size 24
Outer malloc wrapper called on size 8
Allocation of size 8
Outer malloc wrapper called on size 80
Allocation of size 80
Outer malloc wrapper called on size 4080
Allocation of size 4080
Outer malloc wrapper called on size 24
Allocation of size 24
Outer malloc wrapper called on size 4000
Allocation of size 4000
Outer malloc wrapper called on size 1
Allocation of size 1
Outer malloc wrapper called on size 24
Allocation of size 24
Outer malloc wrapper called on size 1
Allocation of size 1
Outer malloc wrapper called on size 80
Allocation of size 80
Outer malloc wrapper called on size 4080
Allocation of size 4080
Outer malloc wrapper called on size 24
Allocation of size 24
Allocation of size 1
Allocation of size 24
Allocation of size 1
Allocation of size 80
Allocation of size 4080
Allocation of size 24
```

Notice that the later mallocs don't have both wrappers applied :)

**Comment by mplegendre** [comment]
> In the first, I'll have to claim ignorance. I can do some research, but I'm not sure where we would get in trouble off the top of my head. I have a hazy recollection that it's possible to manually specify the calling conventions of a function in either C or C++ (fastcall or cdecl or ____), that may be a good hedge.

I don't think specifying calling conventions here is the way to go.  Gotcha is mapping between app-controlled callsites/callees and tool-control wrappers.  We have zero control over the app-controlled side of the calling conventions.  This interface adds a C++ lambda as the target of the callsite, and I don't think you'll ever be able to "extern C" a lambda.  So the tool side is now always C++.  If one side is fixed, and one side is always C++, then there's no place to specify a common calling convention.

> So doing things like "replace mallocs in this loop with MallocDujours" becomes possible

I'm not following this use case. The tool writer doesn't generally understand the application's loops.  The app-writer doesn't understand the dynamic-link/static-link aspects of gotcha.  Who is writing this "replace malloc in a loop" and why?

> I think the thread-safety point is well taken, but that the solution there is documentation

I don't think the tool writer can avoid the thread-safety point.  We could write: "Don't let multiple threads go through your wrappers simultaneously", but that's advice for the tool writer.  It's the application developer who determines they're going to have multiple threads calling malloc simultaneously.

**Comment by DavidPoliakoff** [comment]
> I don't think specifying calling conventions here is the way to go. Gotcha is mapping between app-controlled callsites/callees and tool-control wrappers. We have zero control over the app-controlled side of the calling conventions. This interface adds a C++ lambda as the target of the callsite, and I don't think you'll ever be able to "extern C" a lambda. So the tool side is now always C++. If one side is fixed, and one side is always C++, then there's no place to specify a common calling convention.

Could we find a place this comes up in practice? We can't extern "C" a lambda, but we might be able to specify a calling convention for redirect, which is a static function. Then it calls the lambda, and I'd assume the compiler has to make that a correctly formed call. But I'd want to see an example, if it is a threat I feel there's a mitigation for it. 

>The tool writer doesn't generally understand the application's loops.

I skipped a step here. This part isn't for tools. This is something an application developer might want, that within a region of code they use a memory pool (MallocDujour might be spelled jemalloc), and in other regions they don't, or want to use a different one, or want to pick different malloc based on the requested size of the allocation. This actually gives me an extremely big idea that feels a little bit like Apollo for function calls, but that's another story that I won't explore. It's a very different use case for Gotcha, but one I think could be quite powerful. Actually, that's absurdly powerful, you could imagine that there's a function like "FieldAllocate" in some codes, they might want the underlying malloc to be one way in one part of their code, another way in a different one. The software engineer in me finds this a disgusting answer, but an effective one, essentially adding aspect-oriented programming to parts of C++.

Re: thread-safety, the tool writer can't say "don't let multiple things go through your wrapper simultaneously," but they can say "only initialize or reconfigure my tool in a context where thread safety doesn't matter." In other words, "don't call init_caliper from within threaded code" is something a tool developer could say. The only place I see thread safety coming up is if some of these static data members are modified as some thread is calling the wrapped function, meaning one function hits unwrap as another calls the function, and I think that is certainly solvable socially. Honestly I'm not sure what happens if somebody calls regular gotcha_wrap on a function in a non-threadsafe context, what happens if Thread A gets an unwrapped version and Thread B gets a wrapped version and the wrapper assumes all threads get the wrapped version? I'm missing the "attack surface/bug surface" this exposes.

**Comment by DavidPoliakoff** [comment]
I tested declaring redirect to use the cdecl calling convention, and that works. I doubt this fully solves C->C++ redirect issues, but it does give us a lever

**Pull request closed without merging**
